### ISSUE TITLE
Dont pad está fora do ar.

### ISSUE THREAD

**Issue by julioflima** [victoorlucas/Dontpad#7]
Já que o Dont Pad está fora do ar, deverias subir um demo desse projeto.

Eu usaria. Abraço.

**Comment by victorlucss** [comment]
Olá, @julioflima, desculpa pela demora. Irei subir nos próximos meses uma versão mais atualizada deste repositório afim de servir melhor o propósito dele. De antemão, lhe adiando que tenho agora uma ajudinha de alguns amigos e iremos tentar manter o Fake Dontpad (ou, como chamamos, Padont) no ar 😄

**Comment by victorlucss** [comment]
Oi, @julioflima ! Fico feliz de informar que subi o Padont hoje, segue o link: https://padont.com/

**Comment by julioflima** [comment]
Congratulations on the color design and everything. Great project, I'll share.

**Comment by victorlucss** [comment]
Thanks! @julioflima
